user nginx;
worker_processes 1;
error_log /dev/stderr debug;
pid /var/run/nginx.pid;

events {
	worker_connections 1024;
}

http {
	include 				/etc/nginx/mime.types;
	default_type 			application/octet-stream;
	client_max_body_size	200M;

	# 1. Trust the ingress-nginx internal cluster IPs to find the real IP
    # 10.244.0.0/16 is typical for K8s pod CIDR, adjusting to 0.0.0.0/0 is easiest inside the cluster
	set_real_ip_from		0.0.0.0/0;
    real_ip_header			X-Forwarded-For;
    real_ip_recursive		on;

	log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

	access_log /dev/stdout main;
	error_log /dev/stderr debug;

	sendfile on;
	keepalive_timeout 65;

	server {
		location / {
			root /usr/share/nginx/html;
			index index.html;
			try_files $uri $uri/ /index.html;

			# No proxy occurs
		}
		location /api {
			rewrite /api/(.*) /$1  break;
			proxy_pass https://api.zauartcc.org;
			proxy_ssl_server_name on;

			# Restore real client IP from Cloudflare
			proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
		}
		location /devapi {
			rewrite /devapi/(.*) /$1  break;
			proxy_pass https://devapi.zauartcc.org;
			proxy_ssl_server_name on;

			# Restore real client IP from Cloudflare
			proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
		}
		location /metar {
			rewrite /metar/(.*) /$1  break;
			proxy_pass https://metar.vatsim.net;
			proxy_ssl_server_name on;

			# Restore real client IP from Cloudflare
			proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
		}
		location /vatusa {
			rewrite /vatusa/(.*) /$1  break;
			proxy_pass https://api.vatusa.net/v2;
			proxy_ssl_server_name on;

			# Restore real client IP from Cloudflare
			proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
		}

		error_page 500 502 503 504 /50x.html;

		location = /50x.html {
			root /usr/share/nginx/html;
		}
	}
}
